FROM jrottenberg/ffmpeg:4.1-ubuntu
RUN apt-get update && apt-get install -y python3 python3-pip ffmpeg libsm6 libxext6 libxrender-dev
RUN pip3 install redis opencv-python scikit-video numpy tqdm
COPY job.py job.py
