apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-model
  labels:
    app: color-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: color-model
  template:
    metadata:
      labels:
        app: color-model
    spec:
      containers:
        - name: color-model
          image: registry.datexis.com/s76413/colormodel
          env:
          - name: LANG
            value: 'C.UTF-8'
          - name: VIDEOPATH
            value: '/pvc'
          resources:      
            requests:
              cpu: 1
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - name: fsmount
              mountPath: /network-ceph
            - name: dshm
              mountPath: /dev/shm
      nodeSelector:
        gpu: k80
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: fsmount                                              
          flexVolume:                                                
            driver: ceph.rook.io/rook                                
            fsType: ceph                                             
            options:                                                 
              fsName: home                                           
              clusterNamespace: rook-ceph
      imagePullSecrets:
        - name: private-registry-auth
