FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-devel

RUN apt-get update && apt-get install -y htop tmux ffmpeg vim openssh-server && rm -rf /var/lib/apt/lists/*

RUN mkdir /var/run/sshd
RUN echo 'root:screencast' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# SSH login fix. Otherwise user is kicked off after login
RUN sed 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' -i /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22

RUN conda update -y -n base -c defaults conda
RUN conda install -y -c conda-forge opencv scikit-video
RUN pip install scikit-image hdf5plugin h5py
RUN conda install -y pylint tensorboard
RUN conda install -c anaconda scikit-learn

COPY dataset dataset
COPY model model
COPY inference.py .
COPY training.py .
COPY training_lstm.py .
COPY conversion_utils.py .
COPY sshd_config /etc/ssh/sshd_config
COPY training_parallel.py .
COPY run.sh .
